# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tony Wu
url:              http://www.tonyhuiwu.com
paginate:         3
baseurl:          /
author:
  name:           Tony Wu
  url:            http://www.tonyhuiwu.com
  email:          tonyhuiwu@gmail.com

# Custom vars
excerpt_separator: <!--more-->
pages_list:
  About : '/about'
  Archive: '/archive'
  Projects: '/projects'
version:          1.0.0
github:
  repo:
