# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tony Wu
url:              http://www.tonyhuiwu.com
paginate:         3
baseurl:          /
author:
  name:           Tony Wu
  url:            http://www.google.ca
  email:          tonyhuiwu@gmail.com

# Custom vars
excerpt_separator: <!--more-->
pages_list:       
  About : '/about'
  Projects: '/projects'
  Resume:   'images/resume.pdf'
version:          1.0.0
github:
  repo:           
